/**
 * NOTE UIDs — the public, shareable reference code for Library resources.
 *
 * A note is tagged in any group chat as [CC-NOTE-XXXX] (or just the bare
 * code) and rendered there as a dark Library card with the contributor's
 * name; tapping it deep-links to /notes?uid=CC-NOTE-XXXX where the note is
 * scrolled to and highlighted.
 *
 * The alphabet deliberately excludes I, O, 0 and 1 so codes survive being
 * read aloud or typed from memory. Parsing is a pure regex so both the chat
 * renderer and the tests share one definition of "looks like a note tag".
 */

export const NOTE_UID_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'

/** CC-NOTE-XXXX — generated by the trg_notes_note_uid DB trigger. */
export const NOTE_UID_REGEX = /CC-NOTE-[A-HJ-NP-Z2-9]{4}/g

/** Exactly one full code, anchored — for validating a user-supplied uid param. */
export const NOTE_UID_EXACT = /^CC-NOTE-[A-HJ-NP-Z2-9]{4}$/

/** Split message text into plain parts, @mentions and note-UID tags. */
export function splitMessageParts(body: string): string[] {
  if (!body) return []
  return body.split(/(@[a-zA-Z0-9_]{2,32}|CC-NOTE-[A-HJ-NP-Z2-9]{4})/g)
}

export function isNoteUid(part: string): boolean {
  return NOTE_UID_EXACT.test(part)
}

/** Deep link target for a note code. */
export function noteUidHref(uid: string): string {
  return `/notes?uid=${encodeURIComponent(uid)}`
}
