/**
 * PROGRAMMING ARENA — MCQ question bank + round picker.
 *
 * One reusable engine, different question data (spec §10): every topic runs
 * through the same ArenaQuiz component. This is the single question source
 * for the Programming Arena — a future compiler/judge phase can add a
 * `kind: 'code'` variant without touching the UI flow.
 *
 * Practice-only by design: results render in the UI and nothing is written
 * to the DB, so no existing scoring/leaderboard system is bypassed or faked.
 *
 * BATCHING: the original 60 seeded questions have no metadata and must stay
 * untouched. Batch-2 questions carry stable ids ({topic}-011..{topic}-050),
 * subtopic, explanation, difficulty and points. 50 questions per topic.
 */

export type ArenaTopicKey = 'java' | 'python' | 'dsa' | 'cpp' | 'javascript' | 'dbms'

export interface ArenaQuestion {
  q: string
  options: string[]
  answer: number // index into options
  // ── Batch-2 fields (optional so the original 60 seeded questions stay
  // valid unchanged; ArenaQuiz only reads q/options/answer) ──
  id?: string
  subtopic?: string
  explanation?: string
  difficulty?: 'easy' | 'medium' | 'hard'
  points?: number
}

export interface ArenaTopic {
  key: ArenaTopicKey
  title: string
  desc: string
  icon: string
  questions: ArenaQuestion[]
}

const P = { easy: 10, medium: 20, hard: 30 } as const

export const ARENA_TOPICS: ArenaTopic[] = [
  {
    key: 'java',
    title: 'Java',
    desc: 'Core Java & JVM',
    icon: '/icons/java.svg',
    questions: [
      {
        q: 'Which keyword is used to inherit a class in Java?',
        options: ['implements', 'extends', 'inherits', 'super'],
        answer: 1,
      },
      { q: 'What is the default value of an int field in Java?', options: ['null', 'undefined', '0', '-1'], answer: 2 },
      {
        q: 'Which collection guarantees insertion order?',
        options: ['HashSet', 'LinkedHashSet', 'TreeSet', 'Hashtable'],
        answer: 1,
      },
      {
        q: 'JVM stands for?',
        options: ['Java Virtual Machine', 'Java Verified Module', 'Just-in Virtual Memory', 'Java Variable Manager'],
        answer: 0,
      },
      {
        q: 'Which is NOT an OOP pillar?',
        options: ['Encapsulation', 'Polymorphism', 'Compilation', 'Inheritance'],
        answer: 2,
      },
      { q: 'Strings in Java are…', options: ['mutable', 'immutable', 'volatile', 'transient'], answer: 1 },
      {
        q: 'Which method is the entry point of a Java program?',
        options: ['start()', 'init()', 'main()', 'run()'],
        answer: 2,
      },
      {
        q: 'final variable means…',
        options: ['can be reassigned once', 'cannot be reassigned', 'thread-safe', 'garbage collected first'],
        answer: 1,
      },
      {
        q: 'Which exception is checked at compile time?',
        options: ['NullPointerException', 'IOException', 'ArithmeticException', 'ClassCastException'],
        answer: 1,
      },
      {
        q: 'interface methods are by default…',
        options: ['private', 'protected', 'public abstract', 'static'],
        answer: 2,
      },
      {
        id: 'java-011',
        subtopic: 'OOP',
        difficulty: 'easy',
        points: P.easy,
        q: 'Wrapping data and the methods that operate on it into a single unit is called…',
        options: ['Encapsulation', 'Inheritance', 'Abstraction', 'Polymorphism'],
        answer: 0,
        explanation:
          'Encapsulation bundles fields and methods together and restricts direct access to internal state (e.g. private fields + getters/setters).',
      },
      {
        id: 'java-012',
        subtopic: 'OOP',
        difficulty: 'easy',
        points: P.easy,
        q: 'Method overloading is resolved…',
        options: [
          'at runtime by the JVM',
          'at compile time by the compiler',
          'by the garbage collector',
          'by the class loader',
        ],
        answer: 1,
        explanation:
          'Overloading (same name, different parameter lists) is static binding — the compiler picks the signature at compile time.',
      },
      {
        id: 'java-013',
        subtopic: 'OOP',
        difficulty: 'medium',
        points: P.medium,
        q: 'Which is TRUE about constructors in Java?',
        options: [
          'They can be marked final',
          'They cannot be inherited by subclasses',
          'They must be public',
          'They can be static',
        ],
        answer: 1,
        explanation:
          'Constructors are not members that are inherited; a subclass defines its own constructors and chains via super(). final/static constructors are illegal.',
      },
      {
        id: 'java-014',
        subtopic: 'OOP',
        difficulty: 'medium',
        points: P.medium,
        q: 'class A { void m() {} } class B extends A { void m(int x) {} } — B.m(int) is…',
        options: ['an override of A.m', 'an overload relative to A.m', 'a compile error', 'field shadowing'],
        answer: 1,
        explanation:
          'Same name but a different parameter list means overloading, not overriding. Overriding requires the identical signature.',
      },
      {
        id: 'java-015',
        subtopic: 'OOP',
        difficulty: 'medium',
        points: P.medium,
        q: 'An explicit super(...) call inside a constructor…',
        options: [
          'may appear anywhere',
          'must be the first statement',
          'must be the last statement',
          'is only allowed in static blocks',
        ],
        answer: 1,
        explanation:
          'The superclass must be initialised before the subclass body runs, so an explicit super(...) must be the first statement of the constructor.',
      },
      {
        id: 'java-016',
        subtopic: 'OOP',
        difficulty: 'medium',
        points: P.medium,
        q: 'Fields declared in an interface are implicitly…',
        options: ['private', 'public static final', 'protected transient', 'package-private'],
        answer: 1,
        explanation:
          'Interface fields are constants: implicitly public, static and final, because interfaces describe a contract, not mutable state.',
      },
      {
        id: 'java-017',
        subtopic: 'OOP',
        difficulty: 'medium',
        points: P.medium,
        q: 'Runtime polymorphism in Java is achieved through…',
        options: [
          'method overloading',
          'method overriding with a superclass reference',
          'static methods',
          'final methods',
        ],
        answer: 1,
        explanation:
          'Dynamic dispatch: when a superclass reference points to a subclass object, the overridden method chosen is based on the actual object at runtime.',
      },
      {
        id: 'java-018',
        subtopic: 'OOP',
        difficulty: 'hard',
        points: P.hard,
        q: 'A a = new B(); a.m(); where B overrides m() — which implementation runs?',
        options: [
          "A's m(), because the reference type is A",
          "B's m(), because of dynamic dispatch",
          'Compile error',
          'Depends on the JVM version',
        ],
        answer: 1,
        explanation:
          'The compiler checks A has m(), but at runtime the JVM dispatches to the actual object type — B.m() runs (virtual method invocation).',
      },
      {
        id: 'java-019',
        subtopic: 'Collections',
        difficulty: 'easy',
        points: P.easy,
        q: 'Which collection interface stores unique key-value mappings?',
        options: ['List', 'Set', 'Map', 'Queue'],
        answer: 2,
        explanation:
          'Map stores key→value pairs with unique keys. Note: Map is not part of the Collection interface hierarchy.',
      },
      {
        id: 'java-020',
        subtopic: 'Collections',
        difficulty: 'easy',
        points: P.easy,
        q: 'Random access (get(i)) is faster in…',
        options: ['ArrayList — O(1) array indexing', 'LinkedList — O(1)', 'Both are equal', 'LinkedList — O(log n)'],
        answer: 0,
        explanation:
          'ArrayList backs onto an array so get(i) is O(1). LinkedList must traverse nodes from the nearest end: O(n).',
      },
      {
        id: 'java-021',
        subtopic: 'Collections',
        difficulty: 'easy',
        points: P.easy,
        q: 'Which Set keeps its elements in sorted order?',
        options: ['HashSet', 'LinkedHashSet', 'TreeSet', 'None of them can'],
        answer: 2,
        explanation: 'TreeSet is backed by a red-black tree and keeps elements in their natural (or Comparator) order.',
      },
      {
        id: 'java-022',
        subtopic: 'Collections',
        difficulty: 'medium',
        points: P.medium,
        q: 'How many null keys can a HashMap hold?',
        options: ['None', 'Exactly one', 'Unlimited', 'Depends on the load factor'],
        answer: 1,
        explanation: 'HashMap allows a single null key (stored in bucket 0) and any number of null values.',
      },
      {
        id: 'java-023',
        subtopic: 'Collections',
        difficulty: 'medium',
        points: P.medium,
        q: 'Modifying a HashMap while iterating it (outside the iterator) causes…',
        options: [
          'ConcurrentModificationException on the next advance',
          'Silent corruption',
          'Compilation error',
          'Nothing — iterators are snapshots',
        ],
        answer: 0,
        explanation:
          'HashMap iterators are fail-fast: they track structural modifications and throw ConcurrentModificationException when the count changes unexpectedly.',
      },
      {
        id: 'java-024',
        subtopic: 'Collections',
        difficulty: 'medium',
        points: P.medium,
        q: 'new HashMap<>(16) with default load factor 0.75 resizes when the…',
        options: ['12th entry is added', '16th entry is added', '8th entry is added', 'map is read'],
        answer: 0,
        explanation:
          'Threshold = capacity × load factor = 16 × 0.75 = 12. Adding the 13th entry triggers a resize to 32 buckets.',
      },
      {
        id: 'java-025',
        subtopic: 'Collections',
        difficulty: 'medium',
        points: P.medium,
        q: 'Which legacy collection is synchronized (thread-safe)?',
        options: ['ArrayList', 'Vector', 'LinkedList', 'PriorityQueue'],
        answer: 1,
        explanation:
          'Vector is the legacy synchronized list; ArrayList/LinkedList/PriorityQueue are not thread-safe (use CopyOnWriteArrayList or Collections.synchronizedList instead).',
      },
      {
        id: 'java-026',
        subtopic: 'Collections',
        difficulty: 'hard',
        points: P.hard,
        q: 'In a TreeSet, if compareTo returns 0 for two distinct objects, inserting the second one…',
        options: [
          'stores both',
          'is ignored — the Set treats it as a duplicate',
          'replaces the first',
          'throws ClassCastException',
        ],
        answer: 1,
        explanation:
          'TreeSet uses compareTo for both ordering AND equality. A 0 result means "same element", so the new insert is dropped.',
      },
      {
        id: 'java-027',
        subtopic: 'Collections',
        difficulty: 'hard',
        points: P.hard,
        q: 'map.computeIfAbsent(key, fn) when the key ALREADY exists…',
        options: [
          'overwrites the value with fn(key)',
          'does nothing and returns the existing value',
          'throws IllegalStateException',
          'removes the entry',
        ],
        answer: 1,
        explanation:
          'computeIfAbsent only computes and inserts when the key is absent (or mapped to null); otherwise it returns the current mapping untouched.',
      },
      {
        id: 'java-028',
        subtopic: 'Exceptions',
        difficulty: 'easy',
        points: P.easy,
        q: 'The parent class of both exceptions and errors in Java is…',
        options: ['Exception', 'Throwable', 'Error', 'RuntimeException'],
        answer: 1,
        explanation: 'Throwable is the root; Exception (recoverable) and Error (serious JVM problems) extend it.',
      },
      {
        id: 'java-029',
        subtopic: 'Exceptions',
        difficulty: 'easy',
        points: P.easy,
        q: 'The finally block runs…',
        options: [
          'only when an exception is thrown',
          'only on success',
          'in all cases except System.exit / JVM death',
          'never if there is a return in try',
        ],
        answer: 2,
        explanation:
          'finally executes whether or not an exception occurs — the only escapes are System.exit(), JVM crash, or an infinite loop in try.',
      },
      {
        id: 'java-030',
        subtopic: 'Exceptions',
        difficulty: 'medium',
        points: P.medium,
        q: 'A try block WITHOUT catch is legal when…',
        options: ['never', 'it is followed by finally', 'it is inside a loop', 'the method is static'],
        answer: 1,
        explanation: 'try-finally is valid Java: resources can be cleaned up while exceptions propagate to the caller.',
      },
      {
        id: 'java-031',
        subtopic: 'Exceptions',
        difficulty: 'medium',
        points: P.medium,
        q: 'Unchecked exceptions are subclasses of…',
        options: ['Exception directly', 'RuntimeException and Error', 'Throwable only', 'IOException'],
        answer: 1,
        explanation:
          'RuntimeException (and Error) descendants are unchecked — no throws declaration or try/catch is required by the compiler.',
      },
      {
        id: 'java-032',
        subtopic: 'Exceptions',
        difficulty: 'medium',
        points: P.medium,
        q: 'When catching IOException and its subclass FileNotFoundException, the order must be…',
        options: [
          'either order compiles',
          'subclass first — superclass first makes the subclass catch unreachable',
          'superclass first',
          'they cannot both be caught',
        ],
        answer: 1,
        explanation:
          'A catch for the superclass would consume every subclass exception, so the compiler flags the later subclass catch as unreachable code.',
      },
      {
        id: 'java-033',
        subtopic: 'Exceptions',
        difficulty: 'medium',
        points: P.medium,
        q: 'The `throws` keyword in a method signature…',
        options: [
          'throws an exception object',
          'declares exception types the method may propagate',
          'guarantees an exception occurs',
          'replaces try/catch at runtime',
        ],
        answer: 1,
        explanation:
          'throws declares checked exceptions a method can propagate, forcing callers to handle or re-declare them. throw actually raises an instance.',
      },
      {
        id: 'java-034',
        subtopic: 'Exceptions',
        difficulty: 'hard',
        points: P.hard,
        q: 'If a finally block contains a return statement, it…',
        options: [
          'is a compile error',
          'overrides any return/exception from try or catch',
          'is ignored by the JVM',
          'runs after the try return value is already delivered',
        ],
        answer: 1,
        explanation:
          'A return in finally discards the pending try/catch result (even a pending exception!) — a well-known anti-pattern that silently swallows failures.',
      },
      {
        id: 'java-035',
        subtopic: 'Multithreading',
        difficulty: 'easy',
        points: P.easy,
        q: 'A thread in Java can be created by…',
        options: [
          'only extending Thread',
          'only implementing Runnable',
          'extending Thread or implementing Runnable (with a Thread wrapper)',
          'annotations',
        ],
        answer: 2,
        explanation:
          'Both work: subclass Thread, or implement Runnable and pass it to a Thread. Runnable is preferred — it leaves the class free to extend something else.',
      },
      {
        id: 'java-036',
        subtopic: 'Multithreading',
        difficulty: 'easy',
        points: P.easy,
        q: 'The synchronized keyword prevents…',
        options: [
          'memory leaks',
          'two threads entering the same monitor-guarded section simultaneously',
          'all exceptions',
          'deadlocks',
        ],
        answer: 1,
        explanation:
          'synchronized grants mutually exclusive access to a lock/monitor. It does NOT prevent deadlocks — bad lock ordering can still deadlock.',
      },
      {
        id: 'java-037',
        subtopic: 'Multithreading',
        difficulty: 'medium',
        points: P.medium,
        q: 'Calling t.run() directly instead of t.start()…',
        options: [
          'starts the thread on a new call stack',
          'executes run() in the CURRENT thread',
          'is a compile error',
          'throws IllegalThreadStateException',
        ],
        answer: 1,
        explanation:
          'start() asks the JVM to spawn a new call stack and invoke run() there. run() alone is just a normal method call — no concurrency.',
      },
      {
        id: 'java-038',
        subtopic: 'Multithreading',
        difficulty: 'medium',
        points: P.medium,
        q: 'The volatile modifier on a field guarantees…',
        options: [
          'atomic increments',
          'visibility of writes across threads',
          'exclusive locking',
          'that the field cannot be null',
        ],
        answer: 1,
        explanation:
          'volatile establishes happens-before visibility: readers always see the latest write. It does NOT make compound actions like count++ atomic.',
      },
      {
        id: 'java-039',
        subtopic: 'Multithreading',
        difficulty: 'medium',
        points: P.medium,
        q: 'Object.wait() can legally be called…',
        options: [
          'from any method',
          "only while holding that object's monitor (inside synchronized)",
          'only from the main thread',
          'inside static blocks only',
        ],
        answer: 1,
        explanation:
          'wait() releases the monitor, so the thread must own it first — otherwise IllegalMonitorStateException is thrown.',
      },
      {
        id: 'java-040',
        subtopic: 'Multithreading',
        difficulty: 'medium',
        points: P.medium,
        q: 'Immediately after Thread.sleep(1000) completes, the thread is in the…',
        options: ['NEW state', 'RUNNABLE (ready-to-run) state', 'TERMINATED state', 'permanently BLOCKED state'],
        answer: 1,
        explanation:
          'After the sleep expires the thread leaves TIMED_WAITING and becomes runnable again — it competes for the CPU but may not run instantly.',
      },
      {
        id: 'java-041',
        subtopic: 'Multithreading',
        difficulty: 'hard',
        points: P.hard,
        q: 'Thread 1 locks A then B; Thread 2 locks B then A. This…',
        options: [
          'is always safe',
          "can deadlock — each waits for the other's lock",
          'is prevented automatically by the JVM',
          'causes a livelock, not a deadlock',
        ],
        answer: 1,
        explanation:
          'Circular wait is one of the four deadlock conditions. Fix by acquiring locks in a globally consistent order or using tryLock with timeout.',
      },
      {
        id: 'java-042',
        subtopic: 'Multithreading',
        difficulty: 'hard',
        points: P.hard,
        q: 'AtomicInteger.incrementAndGet() achieves atomicity without locks using…',
        options: [
          'operating-system mutexes',
          'hardware compare-and-swap (CAS) instructions',
          'volatile alone',
          'synchronizing on the Integer cache',
        ],
        answer: 1,
        explanation:
          'java.util.concurrent atomics use CAS loops (Unsafe/VarHandle): read a value, compute, and swap only if unchanged — retrying on contention.',
      },
      {
        id: 'java-043',
        subtopic: 'JVM & Memory',
        difficulty: 'easy',
        points: P.easy,
        q: 'Java bytecode (.class files) is executed by…',
        options: ['the operating system directly', 'the JVM', 'the CPU as native code', 'the browser'],
        answer: 1,
        explanation:
          'javac compiles source to bytecode; the JVM interprets/JIT-compiles it for the host platform — that is what makes Java portable.',
      },
      {
        id: 'java-044',
        subtopic: 'JVM & Memory',
        difficulty: 'easy',
        points: P.easy,
        q: 'The JDK contains…',
        options: [
          'only the runtime',
          'the JRE plus development tools (javac, javadoc, jdb)',
          'only the compiler',
          'a browser plugin',
        ],
        answer: 1,
        explanation: 'JDK = JRE + tooling. To just run compiled programs, the JRE (or a runtime image) is enough.',
      },
      {
        id: 'java-045',
        subtopic: 'JVM & Memory',
        difficulty: 'medium',
        points: P.medium,
        q: 'The garbage collector reclaims objects that…',
        options: [
          'have been alive over 30 seconds',
          'are no longer reachable from any live reference',
          'are primitives',
          'are stored in static fields',
        ],
        answer: 1,
        explanation:
          'GC uses reachability, not age. An object referenced by a live static field or thread stack root never becomes collectible.',
      },
      {
        id: 'java-046',
        subtopic: 'JVM & Memory',
        difficulty: 'medium',
        points: P.medium,
        q: 'StackOverflowError is typically caused by…',
        options: ['a full heap', 'deep or infinite recursion', 'too many live objects', 'oversized arrays'],
        answer: 1,
        explanation:
          'Each method call consumes a stack frame; unbounded recursion exhausts the per-thread stack. Heap pressure throws OutOfMemoryError instead.',
      },
      {
        id: 'java-047',
        subtopic: 'JVM & Memory',
        difficulty: 'medium',
        points: P.medium,
        q: 'String s1 = "hi"; String s2 = "hi"; (s1 == s2) is…',
        options: [
          'false — different objects',
          'true — both refer to the same pooled literal',
          'a compile error',
          'true only on the first call',
        ],
        answer: 1,
        explanation:
          'String literals are interned in the string pool, so identical literals share one object. Use equals() for content comparison; new String("hi") creates a separate heap object.',
      },
      {
        id: 'java-048',
        subtopic: 'JVM & Memory',
        difficulty: 'hard',
        points: P.hard,
        q: 'java.lang.OutOfMemoryError is thrown when…',
        options: [
          'the call stack is exhausted',
          'heap or metaspace cannot satisfy an allocation',
          'the GC pauses too long',
          'too many threads are created',
        ],
        answer: 1,
        explanation:
          'OOM means an allocation (heap objects or metaspace class metadata) cannot be satisfied even after GC. Stack exhaustion is the separate StackOverflowError.',
      },
      {
        id: 'java-049',
        subtopic: 'JVM & Memory',
        difficulty: 'hard',
        points: P.hard,
        q: 'Classes in Java are loaded…',
        options: [
          'all at JVM startup',
          'lazily — on first active use',
          'by the garbage collector',
          'during compilation',
        ],
        answer: 1,
        explanation:
          'The class loader loads, links and initialises a class at its first active use (new, static access, reflection), keeping startup cost proportional to what runs.',
      },
      {
        id: 'java-050',
        subtopic: 'Language Basics',
        difficulty: 'medium',
        points: P.medium,
        q: 'For objects, the == operator compares…',
        options: [
          'contents, like equals()',
          'references — whether both point to the same object',
          'hash codes',
          'class names',
        ],
        answer: 1,
        explanation:
          '== tests reference identity for objects (and values for primitives). Content equality must go through equals(), which classes like String override.',
      },
    ],
    // __PYTHON__
  },
  {
    key: 'python',
    title: 'Python',
    desc: 'Python concepts & stdlib',
    icon: '/icons/python.svg',
    questions: [
      { q: 'Which is a mutable collection?', options: ['tuple', 'str', 'list', 'bytes'], answer: 2 },
      { q: 'What does len("hello") return?', options: ['4', '5', '6', 'Error'], answer: 1 },
      { q: 'Which keyword defines a function?', options: ['func', 'def', 'fn', 'lambda'], answer: 1 },
      {
        q: 'Python dictionaries are…',
        options: ['ordered by insertion (3.7+)', 'always sorted', 'unordered forever', 'immutable'],
        answer: 0,
      },
      { q: 'What is PEP 8?', options: ['A framework', 'Style guide', 'A package manager', 'A debugger'], answer: 1 },
      {
        q: 'Which creates a list of squares 0-4?',
        options: ['[x**2 for x in range(5)]', '[x^2 in range(5)]', 'map(x**2, 5)', 'list(x**2 while x<5)'],
        answer: 0,
      },
      { q: 'pip is used for…', options: ['package management', 'testing', 'linting', 'compiling'], answer: 0 },
      {
        q: 'What does `with open(f) as x:` ensure?',
        options: ['faster IO', 'file gets closed', 'file is read-only', 'async read'],
        answer: 1,
      },
      { q: 'None is…', options: ['an empty string', 'zero', 'a singleton object', 'an error'], answer: 2 },
      { q: 'Which is NOT a Python data type?', options: ['set', 'frozenset', 'char', 'complex'], answer: 2 },
      {
        id: 'python-011',
        subtopic: 'Data Structures',
        difficulty: 'easy',
        points: P.easy,
        q: 'Which collection forbids duplicate elements?',
        options: ['list', 'tuple', 'set', 'bytearray'],
        answer: 2,
        explanation:
          'A set stores unique, hashable members — adding an existing element is a no-op. Lists and tuples keep duplicates by design.',
      },
      {
        id: 'python-012',
        subtopic: 'Data Structures',
        difficulty: 'easy',
        points: P.easy,
        q: 'Tuples are preferred over lists when the data…',
        options: ['will change often', 'is fixed-shape / read-only', 'is numeric only', 'must be sorted'],
        answer: 1,
        explanation:
          'Tuples are immutable and hashable — ideal for fixed records and dict keys. Lists suit homogeneous, mutating collections.',
      },
      {
        id: 'python-013',
        subtopic: 'Data Structures',
        difficulty: 'medium',
        points: P.medium,
        q: 'fromkeys pitfall: dict.fromkeys([1,2], []) then appending to one value…',
        options: [
          'appends to that key only',
          'appends to EVERY value — they alias one list object',
          'raises ValueError',
          'removes the key',
        ],
        answer: 1,
        explanation:
          'fromkeys evaluates the default ONCE, so every key points to the same list object. Mutable defaults shared like this are a classic bug.',
      },
      {
        id: 'python-014',
        subtopic: 'Data Structures',
        difficulty: 'medium',
        points: P.medium,
        q: 'The defaultdict(list) from the collections module…',
        options: [
          'sorts keys automatically',
          'auto-creates an empty list on first missing-key access',
          'is immutable',
          'cannot be iterated',
        ],
        answer: 1,
        explanation:
          'defaultdict calls the factory for missing keys, so d[k].append(x) works without checking membership first.',
      },
      {
        id: 'python-015',
        subtopic: 'Data Structures',
        difficulty: 'medium',
        points: P.medium,
        q: 'a = [1,2,3]; b = a; b.append(4) — what is len(a)?',
        options: ['3', '4', '1', 'raises an error'],
        answer: 1,
        explanation:
          'b = a copies the REFERENCE, not the list — both names point to one object, so the append is visible through a.',
      },
      {
        id: 'python-016',
        subtopic: 'Data Structures',
        difficulty: 'hard',
        points: P.hard,
        q: 'a = [1,2,3]; b = a[:]; a += [4] — len(b) is…',
        options: [
          '3 — b is an independent shallow copy',
          '4 — += mutates shared state',
          '0',
          'error: cannot concatenate',
        ],
        answer: 0,
        explanation:
          'a[:] slices out a new list. Note: += mutates a in place, but b already points elsewhere. (Shallow copy still shares INNER objects.)',
      },
      {
        id: 'python-017',
        subtopic: 'Functions',
        difficulty: 'easy',
        points: P.easy,
        q: 'def f(x, y=2): ... — calling f(5) sets…',
        options: ['x=5, y=2', 'x=5, y=None', 'TypeError', 'x=2, y=5'],
        answer: 0,
        explanation: 'Positional 5 binds to x; y keeps its default value 2.',
      },
      {
        id: 'python-018',
        subtopic: 'Functions',
        difficulty: 'easy',
        points: P.easy,
        q: '*args in a function signature collects…',
        options: [
          'keyword arguments into a dict',
          'extra positional arguments into a tuple',
          'only the first argument',
          'default values',
        ],
        answer: 1,
        explanation:
          '*args gathers surplus positional args as a tuple; **kwargs gathers surplus keyword args as a dict.',
      },
      {
        id: 'python-019',
        subtopic: 'Functions',
        difficulty: 'medium',
        points: P.medium,
        q: 'A default argument evaluated at definition time — def f(x=[]): — is dangerous because…',
        options: [
          'lists are slow',
          'the same list persists across calls that omit x',
          'Python forbids mutable defaults',
          'x becomes global',
        ],
        answer: 1,
        explanation:
          'Defaults are evaluated once at def time. Mutations persist between calls — the classic mutable-default trap; use x=None and create inside.',
      },
      {
        id: 'python-020',
        subtopic: 'Functions',
        difficulty: 'medium',
        points: P.medium,
        q: 'A lambda in Python can contain…',
        options: ['multiple statements', 'a single expression', 'loops', 'its own docstring'],
        answer: 1,
        explanation:
          'Lambda is an expression-based anonymous function — one expression only. For statements, define a normal function.',
      },
      {
        id: 'python-021',
        subtopic: 'Functions',
        difficulty: 'medium',
        points: P.medium,
        q: 'def f(*, key): ... — calling f(3)…',
        options: ['binds 3 to key', 'raises TypeError — key is keyword-only', 'ignores 3', 'sets key=None'],
        answer: 1,
        explanation: 'The bare * makes everything after it keyword-only; a positional call fails with TypeError.',
      },
      {
        id: 'python-022',
        subtopic: 'Functions',
        difficulty: 'hard',
        points: P.hard,
        q: 'A closure over a loop variable: fs = [lambda: i for i in range(3)]; [f() for f in fs] returns…',
        options: ['[0, 1, 2]', '[2, 2, 2] — all share the final i', '[3, 3, 3] — i is out of range', 'a TypeError'],
        answer: 1,
        explanation:
          'Closures capture the VARIABLE, not its value at creation. After the loop, i is 2 for all three lambdas. Use default-arg binding: lambda i=i: i.',
      },
      {
        id: 'python-023',
        subtopic: 'Functions',
        difficulty: 'hard',
        points: P.hard,
        q: 'Inside a nested function assigning to the enclosing scope’s variable requires…',
        options: ['global', 'nonlocal', 'static', 'nothing — it works by default'],
        answer: 1,
        explanation:
          'Assignment rebinds in the LOCAL scope by default; nonlocal targets the nearest enclosing function scope (global targets module scope).',
      },
      {
        id: 'python-024',
        subtopic: 'OOP',
        difficulty: 'easy',
        points: P.easy,
        q: 'The first parameter of an instance method is conventionally named…',
        options: ['cls', 'this', 'self', 'me'],
        answer: 2,
        explanation:
          'self receives the instance. It is a convention, not a keyword — but breaking it confuses every reader.',
      },
      {
        id: 'python-025',
        subtopic: 'OOP',
        difficulty: 'easy',
        points: P.easy,
        q: 'Which method acts as the constructor initializer?',
        options: ['__init__', '__new__', '__main__', '__start__'],
        answer: 0,
        explanation:
          '__init__ initialises the (already created) instance; __new__ actually creates it — a rarely-overridden step.',
      },
      {
        id: 'python-026',
        subtopic: 'OOP',
        difficulty: 'medium',
        points: P.medium,
        q: '@staticmethod vs @classmethod: a classmethod receives…',
        options: ['the instance as first arg', 'the class (cls) as first arg', 'no arguments', 'a copy of the module'],
        answer: 1,
        explanation:
          'classmethod binds to the class (useful for alternative constructors); staticmethod binds to neither class nor instance — a plain namespaced function.',
      },
      {
        id: 'python-027',
        subtopic: 'OOP',
        difficulty: 'medium',
        points: P.medium,
        q: 'Python multiple inheritance resolves attribute conflicts using…',
        options: [
          'random choice',
          'the MRO (C3 linearization)',
          'alphabetical class order',
          'last-defined wins, always',
        ],
        answer: 1,
        explanation:
          'The C3 linearization (visible via ClassName.__mro__) defines a deterministic lookup order that keeps subclasses before base classes.',
      },
      {
        id: 'python-028',
        subtopic: 'OOP',
        difficulty: 'medium',
        points: P.medium,
        q: 'Name mangling: self.__secret inside class Foo becomes…',
        options: ['self.__secret unchanged', 'self._Foo__secret', 'self.secret', 'a global'],
        answer: 1,
        explanation:
          'Double-underscore names are rewritten to _ClassName__name — a namespace collision guard for inheritance, NOT true privacy.',
      },
      {
        id: 'python-029',
        subtopic: 'OOP',
        difficulty: 'hard',
        points: P.hard,
        q: 'class A: pass\n a = A(); a.x = 1 — setting attributes on instances works because A…',
        options: ['inherits from dict', 'has a __dict__ by default', 'is decorated', 'is compiled with slots'],
        answer: 1,
        explanation:
          'Ordinary classes store per-instance attributes in a __dict__ (unless __slots__ is defined to forbid it and save memory).',
      },
      {
        id: 'python-030',
        subtopic: 'Errors & Exceptions',
        difficulty: 'easy',
        points: P.easy,
        q: 'Which block ALWAYS runs, exception or not?',
        options: ['else', 'finally', 'except', 'raise'],
        answer: 1,
        explanation:
          'finally runs on success, on exception, even on return — the only escapes are interpreter shutdown or os._exit().',
      },
      {
        id: 'python-031',
        subtopic: 'Errors & Exceptions',
        difficulty: 'easy',
        points: P.easy,
        q: '10 / 0 raises…',
        options: ['ValueError', 'ZeroDivisionError', 'TypeError', 'it returns inf'],
        answer: 1,
        explanation:
          'True division by zero raises ZeroDivisionError (unlike some languages that yield infinity for floats).',
      },
      {
        id: 'python-032',
        subtopic: 'Errors & Exceptions',
        difficulty: 'medium',
        points: P.medium,
        q: 'try/except/else: the else block runs when…',
        options: ['an exception occurs', 'no exception occurs in try', 'finally finishes', 'the function returns'],
        answer: 1,
        explanation:
          'else keeps success-only code out of try, so you never accidentally catch errors raised by the success path itself.',
      },
      {
        id: 'python-033',
        subtopic: 'Errors & Exceptions',
        difficulty: 'medium',
        points: P.medium,
        q: 'Raising a custom application error is done by…',
        options: [
          'class AppError(Exception) + raise AppError("msg")',
          'throw AppError',
          'raise Error(AppError)',
          'AppError.raise()',
        ],
        answer: 0,
        explanation:
          'Subclass Exception and raise an instance. throw is JavaScript, not Python; raise expects an exception class/instance.',
      },
      {
        id: 'python-034',
        subtopic: 'Errors & Exceptions',
        difficulty: 'hard',
        points: P.hard,
        q: 'except Exception as e: ... then re-raising the SAME traceback is done with…',
        options: ['raise e', 'bare raise', 'raise Exception(e)', 're-raise is impossible'],
        answer: 1,
        explanation:
          'A bare raise re-raises the active exception with its original traceback intact; raise e restarts the traceback from this line.',
      },
      {
        id: 'python-035',
        subtopic: 'Modules & Environment',
        difficulty: 'easy',
        points: P.easy,
        q: 'if __name__ == "__main__": guards code that should run…',
        options: ['on import', 'only when the file is executed directly', 'in every thread', 'only on Windows'],
        answer: 1,
        explanation:
          'When imported, __name__ is the module name; only direct execution sets it to "__main__" — the standard entry-point guard.',
      },
      {
        id: 'python-036',
        subtopic: 'Modules & Environment',
        difficulty: 'easy',
        points: P.easy,
        q: 'The standard virtual-environment creation command is…',
        options: ['python -m venv .venv', 'pip install venv', 'python --virtual', 'env make python'],
        answer: 0,
        explanation: 'venv ships with the stdlib; activate it, then pip installs stay isolated per project.',
      },
      {
        id: 'python-037',
        subtopic: 'Modules & Environment',
        difficulty: 'medium',
        points: P.medium,
        q: 'from module import * is discouraged mainly because it…',
        options: [
          'is slower at runtime',
          'pollutes the namespace and hides name origins',
          'fails on packages',
          'imports C extensions only',
        ],
        answer: 1,
        explanation:
          'Wildcard imports make it unclear where names come from and can silently shadow each other — prefer explicit imports.',
      },
      {
        id: 'python-038',
        subtopic: 'Modules & Environment',
        difficulty: 'medium',
        points: P.medium,
        q: 'requirements.txt is consumed by…',
        options: ['pip install -r requirements.txt', 'python -m compileall', 'venv activate', 'importlib.reload'],
        answer: 0,
        explanation:
          'pip reads the pinned requirement list and installs each package (ideally inside an activated venv).',
      },
      {
        id: 'python-039',
        subtopic: 'Modules & Environment',
        difficulty: 'medium',
        points: P.medium,
        q: 'A module is…',
        options: ['any directory', 'a single .py file', 'only a compiled .pyc', 'a zip of classes'],
        answer: 1,
        explanation: 'Module = one .py file; a package is a directory of modules (traditionally with __init__.py).',
      },
      {
        id: 'python-040',
        subtopic: 'Modules & Environment',
        difficulty: 'hard',
        points: P.hard,
        q: 'Circular imports (a imports b, b imports a) are typically fixed by…',
        options: [
          'deleting one module',
          'moving the shared import inside a function or refactoring common code out',
          'importing with *',
          'adding global statements',
        ],
        answer: 1,
        explanation:
          'Deferred (in-function) imports or extracting the shared dependency breaks the import cycle without changing behaviour.',
      },
      {
        id: 'python-041',
        subtopic: 'Data Structures',
        difficulty: 'hard',
        points: P.hard,
        q: 'set membership (x in s) is on average…',
        options: ['O(n) — scans all elements', 'O(1) — hash-based', 'O(log n) — like a tree', 'O(n log n)'],
        answer: 1,
        explanation:
          'Sets/dicts hash their members, so lookups are constant-time on average (worst case degrades only with pathological hash collisions).',
      },
      {
        id: 'python-042',
        subtopic: 'Functions',
        difficulty: 'medium',
        points: P.medium,
        q: 'Generators (functions with yield) are preferred for large sequences because they…',
        options: ['run in C', 'produce items lazily, one at a time', 'are type-safe', 'cache to disk'],
        answer: 1,
        explanation:
          'A generator keeps its state suspended between yields and materialises nothing until requested — O(1) memory for the pipeline instead of a full list.',
      },
      {
        id: 'python-043',
        subtopic: 'Data Structures',
        difficulty: 'medium',
        points: P.medium,
        q: 'sorted(d.items(), key=lambda kv: kv[1]) sorts a dict’s items by…',
        options: ['key', 'value', 'insertion order — key is ignored', 'hash order'],
        answer: 1,
        explanation:
          'kv is a (key, value) tuple; kv[1] is the value. sorted returns a new list and never mutates the dict.',
      },
      {
        id: 'python-044',
        subtopic: 'Data Structures',
        difficulty: 'easy',
        points: P.easy,
        q: 'Slicing s[1:4] on "python" returns…',
        options: ['yth', 'ytho', 'yt', 'pyt'],
        answer: 0,
        explanation: 'Start index 1 inclusive, stop 4 exclusive → characters at 1,2,3 → "yth".',
      },
      {
        id: 'python-045',
        subtopic: 'Data Structures',
        difficulty: 'hard',
        points: P.hard,
        q: '(-7) // 2 in Python 3 evaluates to…',
        options: ['-3', '-4', '-3.5', '3'],
        answer: 1,
        explanation:
          '// is floor division: it rounds toward NEGATIVE infinity, so -7//2 = -4 (while int(-7/2) would give -3). A classic output-prediction trap.',
      },
      {
        id: 'python-046',
        subtopic: 'OOP',
        difficulty: 'medium',
        points: P.medium,
        q: 'Duck typing means…',
        options: [
          'types are checked at compile time',
          'suitability is judged by behaviour/methods, not declared type',
          'all objects inherit from Duck',
          'only birds can fly',
        ],
        answer: 1,
        explanation:
          '"If it quacks like a duck": Python cares whether the object has the needed method, not its class — interfaces are implicit.',
      },
      {
        id: 'python-047',
        subtopic: 'Errors & Exceptions',
        difficulty: 'medium',
        points: P.medium,
        q: 'Assert statements are removed when running with…',
        options: ['python -u', 'python -O (optimize flag)', 'python -i', 'sudo python'],
        answer: 1,
        explanation:
          'Under -O, asserts compile away — never rely on them for validation that must always run (e.g. security checks).',
      },
      {
        id: 'python-048',
        subtopic: 'Functions',
        difficulty: 'easy',
        points: P.easy,
        q: 'The range(2, 10, 3) sequence is…',
        options: ['2, 5, 8', '2, 4, 6, 8', '3, 6, 9', '2, 10'],
        answer: 0,
        explanation: 'Start 2, stop (exclusive) 10, step 3 → 2, 5, 8.',
      },
      {
        id: 'python-049',
        subtopic: 'Data Structures',
        difficulty: 'medium',
        points: P.medium,
        q: 'Dict comprehension {k: k*k for k in range(3)} produces…',
        options: ['{0: 0, 1: 1, 2: 4}', '[0, 1, 4]', '{1, 4}', '{0, 1, 2}'],
        answer: 0,
        explanation:
          'Each k maps to its square — a compact literal for building dicts (same shape as list comprehensions but with key: value).',
      },
      {
        id: 'python-050',
        subtopic: 'OOP',
        difficulty: 'hard',
        points: P.hard,
        q: 'class Dog: legs = 4\n d = Dog(); d.legs = 3 — Dog.legs is now…',
        options: [
          '3',
          '4 — the assignment created an instance attribute shadowing the class one',
          'undefined',
          'an error',
        ],
        answer: 1,
        explanation:
          'd.legs = 3 writes into the instance __dict__, shadowing the class attribute. Dog.legs stays 4; reading d.legs first finds the instance value.',
      },
    ],
  },
  {
    key: 'dsa',
    title: 'DSA',
    desc: 'Algorithms & data structures',
    icon: '/icons/dsa.svg',
    questions: [
      { q: 'Time complexity of binary search?', options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'], answer: 1 },
      { q: 'Which structure is LIFO?', options: ['Queue', 'Stack', 'Heap', 'Trie'], answer: 1 },
      { q: 'Worst case of quicksort?', options: ['O(n log n)', 'O(n²)', 'O(n)', 'O(log n)'], answer: 1 },
      { q: 'BFS uses which structure?', options: ['Stack', 'Queue', 'Heap', 'Set'], answer: 1 },
      { q: 'A hash map gives average lookup of…', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], answer: 0 },
      { q: 'Which sort is stable?', options: ['Quick sort', 'Heap sort', 'Merge sort', 'Selection sort'], answer: 2 },
      { q: 'A binary heap is stored best in a…', options: ['linked list', 'array', 'graph', 'string'], answer: 1 },
      {
        q: 'Detecting a cycle in a linked list: classic approach?',
        options: ['Two pointers', 'Sorting', 'DP table', 'Backtracking'],
        answer: 0,
      },
      {
        q: 'DP is mainly…',
        options: ['recursion without memory', 'memoized subproblems', 'random sampling', 'graph coloring'],
        answer: 1,
      },
      { q: 'Height-balanced BST example?', options: ['AVL tree', 'Trie', 'Segment list', 'Stack'], answer: 0 },
      {
        id: 'dsa-011',
        subtopic: 'Complexity',
        difficulty: 'easy',
        points: P.easy,
        q: 'Nested loop: for i in n { for j in n { work } } — total work is…',
        options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(2ⁿ)'],
        answer: 2,
        explanation:
          'The inner loop runs n times for EACH of the n outer iterations — n × n = n². Stacked nested loops multiply their iteration counts.',
      },
      {
        id: 'dsa-012',
        subtopic: 'Complexity',
        difficulty: 'medium',
        points: P.medium,
        q: 'for i in n { for j in i..n { work } } — the complexity is still…',
        options: ['O(n²) — half the work changes nothing asymptotically', 'O(n)', 'O(n log n)', 'O(n³)'],
        answer: 0,
        explanation:
          'The pair runs n(n+1)/2 ≈ n²/2 times. Constants and lower-order terms drop in Big-O, so it stays quadratic.',
      },
      {
        id: 'dsa-013',
        subtopic: 'Complexity',
        difficulty: 'medium',
        points: P.medium,
        q: 'for i in n { for j in 0..log n } gives…',
        options: ['O(n)', 'O(n log n)', 'O(log n)', 'O(n²)'],
        answer: 1,
        explanation:
          'The outer loop contributes n, the inner log n — they multiply to n log n (typical of efficient sorts like merge sort).',
      },
      {
        id: 'dsa-014',
        subtopic: 'Complexity',
        difficulty: 'hard',
        points: P.hard,
        q: 'Recurrence T(n) = 2T(n/2) + O(n) solves to…',
        options: ['O(n)', 'O(n log n) — Master Theorem case 2', 'O(log n)', 'O(n²)'],
        answer: 1,
        explanation:
          'Two subproblems of half size with linear merge work: merge sort’s exact recurrence — n log n by the Master Theorem (a=2, b=2, f(n)=n).',
      },
      {
        id: 'dsa-015',
        subtopic: 'Arrays & Strings',
        difficulty: 'easy',
        points: P.easy,
        q: 'The two-pointer technique on a SORTED array finds a pair with a given sum in…',
        options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(1)'],
        answer: 2,
        explanation:
          'Start pointers at both ends; each step discards one element definitively, so a single linear pass suffices — given the array is sorted.',
      },
      {
        id: 'dsa-016',
        subtopic: 'Arrays & Strings',
        difficulty: 'medium',
        points: P.medium,
        q: 'The sliding-window pattern applies when the problem asks for…',
        options: ['all permutations', 'a contiguous subarray/substring optimum', 'tree diameters', 'graph coloring'],
        answer: 1,
        explanation:
          'When a constraint defines a window over CONTIGUOUS elements, sliding the window with incremental updates avoids recomputing each from scratch.',
      },
      {
        id: 'dsa-017',
        subtopic: 'Arrays & Strings',
        difficulty: 'medium',
        points: P.medium,
        q: 'Kadane’s algorithm finds the maximum subarray sum in O(n) by…',
        options: [
          'trying all subarrays',
          'extending or restarting the current sum at each element',
          'sorting first',
          'binary searching the answer',
        ],
        answer: 1,
        explanation:
          'Track the best sum ENDING here: either extend the previous run or start fresh at the current element — a greedy DP in one pass.',
      },
      {
        id: 'dsa-018',
        subtopic: 'Arrays & Strings',
        difficulty: 'hard',
        points: P.hard,
        q: 'Prefix sums let you answer any range-sum query [l, r] in…',
        options: ['O(r − l)', 'O(1) after O(n) preprocessing', 'O(log n)', 'O(n log n)'],
        answer: 1,
        explanation:
          'pre[i] = sum of a[0..i], built in O(n); each query is pre[r] − pre[l−1] — constant time. (Frequent updates would need a BIT/segment tree.)',
      },
      {
        id: 'dsa-019',
        subtopic: 'Linked Lists',
        difficulty: 'easy',
        points: P.easy,
        q: 'Inserting at the HEAD of a doubly linked list is…',
        options: ['O(n)', 'O(1)', 'O(log n)', 'O(n log n)'],
        answer: 1,
        explanation: 'Only pointer rewiring is needed — no traversal. (Arrays shift every existing element: O(n).)',
      },
      {
        id: 'dsa-020',
        subtopic: 'Linked Lists',
        difficulty: 'medium',
        points: P.medium,
        q: 'Finding the middle of a linked list in one pass uses…',
        options: [
          'a hash map of indices',
          'fast/slow pointers — fast moves 2×, slow 1×',
          'sorting the list',
          'recursion depth n/2',
        ],
        answer: 1,
        explanation:
          'When fast reaches the end, slow has covered half — Floyd’s tortoise-hare midpoint trick: O(n) time, O(1) space.',
      },
      {
        id: 'dsa-021',
        subtopic: 'Linked Lists',
        difficulty: 'medium',
        points: P.medium,
        q: 'Reversing a linked list iteratively requires…',
        options: ['a second list', 'three pointers: prev, curr, next', 'a stack of all nodes', 'sorting'],
        answer: 1,
        explanation:
          'Walk the list flipping each node’s next to prev, saving the forward node first — O(n) time, O(1) space.',
      },
      {
        id: 'dsa-022',
        subtopic: 'Linked Lists',
        difficulty: 'hard',
        points: P.hard,
        q: 'Floyd’s cycle detection works because, inside a loop, the gap between fast and slow pointers…',
        options: [
          'stays constant',
          'shrinks by one each step until they meet',
          'grows without bound',
          'alternates parity',
        ],
        answer: 1,
        explanation:
          'Each iteration fast gains one position on slow relative to the loop; once both are inside the cycle the relative gap decreases by 1 per step, guaranteeing a meeting.',
      },
      {
        id: 'dsa-023',
        subtopic: 'Stacks & Queues',
        difficulty: 'easy',
        points: P.easy,
        q: 'Balanced-parentheses checking is classically solved with a…',
        options: ['queue', 'stack', 'heap', 'trie'],
        answer: 1,
        explanation: 'Push openers; each closer must match the MOST RECENT opener — exactly LIFO stack behaviour.',
      },
      {
        id: 'dsa-024',
        subtopic: 'Stacks & Queues',
        difficulty: 'medium',
        points: P.medium,
        q: 'The monotonic stack pattern computes “next greater element” in…',
        options: ['O(n²)', 'O(n log n)', 'O(n) — each element is pushed and popped at most once', 'O(n!)'],
        answer: 2,
        explanation:
          'Amortised analysis: although there is an inner pop loop, every index enters and leaves the stack once, so total work is linear.',
      },
      {
        id: 'dsa-025',
        subtopic: 'Stacks & Queues',
        difficulty: 'medium',
        points: P.medium,
        q: 'A queue implemented with two stacks has AMORTISED O(1) dequeue because…',
        options: [
          'every dequeue is O(1)',
          'each element moves between stacks at most twice over its lifetime',
          'the stacks double in size',
          'dequeue is actually O(n) always',
        ],
        answer: 1,
        explanation:
          'Push costs O(1); the transfer stack is refilled only when empty and each element transfers exactly once — the cost amortises to O(1).',
      },
      {
        id: 'dsa-026',
        subtopic: 'Stacks & Queues',
        difficulty: 'hard',
        points: P.hard,
        q: 'The largest rectangle in a histogram is found with a stack in O(n) because…',
        options: [
          'heights are sorted first',
          'bars are popped when a shorter bar appears, finalising their maximal rectangles',
          'it reduces to binary search',
          'a DP table stores all pairs',
        ],
        answer: 1,
        explanation:
          'The stack keeps increasing bars; a shorter bar pops taller ones and each pop fixes that bar’s maximal width — linear despite the nested loop.',
      },
      {
        id: 'dsa-027',
        subtopic: 'Trees',
        difficulty: 'easy',
        points: P.easy,
        q: 'In-order traversal of a Binary SEARCH Tree yields…',
        options: ['insertion order', 'sorted order', 'reverse-sorted order', 'level order'],
        answer: 1,
        explanation: 'Left < root < right is the BST invariant, so left-root-right visits keys in ascending order.',
      },
      {
        id: 'dsa-028',
        subtopic: 'Trees',
        difficulty: 'medium',
        points: P.medium,
        q: 'Level-order (breadth-first) tree traversal uses a…',
        options: ['stack', 'queue', 'priority queue', 'hash set'],
        answer: 1,
        explanation:
          'BFS visits nodes level by level — FIFO ordering via a queue; DFS variants use the call stack or an explicit stack.',
      },
      {
        id: 'dsa-029',
        subtopic: 'Trees',
        difficulty: 'medium',
        points: P.medium,
        q: 'A complete binary tree with n nodes has height…',
        options: ['O(n)', 'O(log n)', 'O(√n)', 'O(n log n)'],
        answer: 1,
        explanation:
          'Each level roughly doubles the node count, so height is ⌊log₂ n⌋ — why heaps guarantee O(log n) operations.',
      },
      {
        id: 'dsa-030',
        subtopic: 'Trees',
        difficulty: 'medium',
        points: P.medium,
        q: 'Two traversals uniquely reconstruct a binary tree when one of them is…',
        options: [
          'any two work',
          'in-order + (pre-order or post-order)',
          'pre-order + post-order always',
          'level + in-order never works',
        ],
        answer: 1,
        explanation:
          'In-order splits left/right subtrees; pre/post-order identifies roots. Pre+post alone is ambiguous for single-child nodes.',
      },
      {
        id: 'dsa-031',
        subtopic: 'Trees',
        difficulty: 'hard',
        points: P.hard,
        q: 'Lowest Common Ancestor with parent pointers and no root access is best solved by…',
        options: [
          'sorting both paths',
          'lifting both nodes to equal depth then moving up in tandem',
          'BFS from each node',
          'in-order traversal',
        ],
        answer: 1,
        explanation:
          'Compute both depths, advance the deeper node until levels match, then step both up together — the first meeting point is the LCA, O(h) time.',
      },
      {
        id: 'dsa-032',
        subtopic: 'Heaps',
        difficulty: 'easy',
        points: P.easy,
        q: 'A min-heap’s smallest element is always at…',
        options: ['the last leaf', 'the root', 'the leftmost leaf', 'any position'],
        answer: 1,
        explanation: 'The heap property (parent ≤ children) pushes the global minimum to the top — peek is O(1).',
      },
      {
        id: 'dsa-033',
        subtopic: 'Heaps',
        difficulty: 'medium',
        points: P.medium,
        q: 'Finding the k LARGEST elements of a stream with O(k) memory uses…',
        options: ['a max-heap of everything', 'a min-heap of size k', 'a sorted array', 'a queue'],
        answer: 1,
        explanation:
          'Keep a size-k min-heap: the root is the k-th largest so far; any bigger incoming element replaces it. The final heap holds the top k.',
      },
      {
        id: 'dsa-034',
        subtopic: 'Heaps',
        difficulty: 'hard',
        points: P.hard,
        q: 'Building a heap from n unordered items bottom-up costs…',
        options: ['O(n log n)', 'O(n) — most nodes sift only a short distance', 'O(log n)', 'O(n²)'],
        answer: 1,
        explanation:
          'Sift-down cost sums over levels: (n/2)·0 + (n/4)·1 + … ≤ n. Floyd’s heapify is linear — cheaper than n individual O(log n) inserts.',
      },
      {
        id: 'dsa-035',
        subtopic: 'Hashing',
        difficulty: 'medium',
        points: P.medium,
        q: 'Open-addressing hash tables degrade most sharply when…',
        options: [
          'keys are strings',
          'the load factor rises — probing runs cluster',
          'values are large',
          'the table is empty',
        ],
        answer: 1,
        explanation:
          'Probing sequences pile up into runs (primary clustering) as occupancy grows — which is why load factors above ~0.7 hurt performance sharply.',
      },
      {
        id: 'dsa-036',
        subtopic: 'Hashing',
        difficulty: 'medium',
        points: P.medium,
        q: 'Two distinct keys hash to the same bucket. The map stores BOTH by…',
        options: [
          'overwriting one',
          'collision resolution — chaining or probing',
          'rejecting the second key',
          'doubling the table immediately',
        ],
        answer: 1,
        explanation:
          'Collisions are expected; chaining keeps a list per bucket while open addressing probes for the next slot. No key is silently dropped.',
      },
      {
        id: 'dsa-037',
        subtopic: 'Graphs',
        difficulty: 'easy',
        points: P.easy,
        q: 'A graph with n nodes and n − 1 edges that is connected is…',
        options: ['a cycle', 'a tree', 'a complete graph', 'disconnected'],
        answer: 1,
        explanation: 'A connected graph with exactly n − 1 edges has no cycles — the definition of a tree.',
      },
      {
        id: 'dsa-038',
        subtopic: 'Graphs',
        difficulty: 'medium',
        points: P.medium,
        q: 'BFS from a source on an UNWEIGHTED graph computes…',
        options: [
          'shortest paths by edge count',
          'minimum spanning tree',
          'strongly connected components',
          'topological order',
        ],
        answer: 0,
        explanation:
          'BFS explores in rings of increasing distance, so the first time a node is reached is via a fewest-edges path — exact shortest paths without weights.',
      },
      {
        id: 'dsa-039',
        subtopic: 'Graphs',
        difficulty: 'medium',
        points: P.medium,
        q: 'Topological sorting is only possible on a…',
        options: ['undirected graph', 'DAG — directed acyclic graph', 'weighted graph', 'tree'],
        answer: 1,
        explanation:
          'A valid linear order respecting all directed edges exists iff the graph has no directed cycle (detected when Kahn’s algorithm emits fewer than n nodes).',
      },
      {
        id: 'dsa-040',
        subtopic: 'Graphs',
        difficulty: 'medium',
        points: P.medium,
        q: 'Union-Find with path compression + union by rank performs each operation in nearly…',
        options: ['O(1)', 'O(α(n)) — inverse Ackermann, effectively constant', 'O(log n)', 'O(n)'],
        answer: 1,
        explanation:
          'The combined heuristics flatten trees so aggressively that amortised cost is α(n) — below 5 for any conceivable n.',
      },
      {
        id: 'dsa-041',
        subtopic: 'Graphs',
        difficulty: 'hard',
        points: P.hard,
        q: 'Dijkstra FAILS (may give wrong answers) when the graph…',
        options: ['is directed', 'has negative edge weights', 'has more than 10⁵ nodes', 'is disconnected'],
        answer: 1,
        explanation:
          'Dijkstra finalises a node on extraction, assuming distances only grow along paths — a negative edge can later shorten a “finished” node. Use Bellman-Ford instead.',
      },
      {
        id: 'dsa-042',
        subtopic: 'Graphs',
        difficulty: 'hard',
        points: P.hard,
        q: 'Detecting a cycle in a DIRECTED graph via DFS requires tracking…',
        options: [
          'visited only',
          'three colours — revisiting a node currently in the recursion stack (gray) means a cycle',
          'edge weights',
          'node degrees only',
        ],
        answer: 1,
        explanation:
          'A back edge to a gray (in-progress) node is a cycle; merely checking “visited” would confuse cross edges with cycles.',
      },
      {
        id: 'dsa-043',
        subtopic: 'Dynamic Programming',
        difficulty: 'easy',
        points: P.easy,
        q: 'DP applies when a problem has…',
        options: [
          'overlapping subproblems + optimal substructure',
          'no repeated states',
          'only one solution path',
          'negative weights',
        ],
        answer: 0,
        explanation:
          'Memoising overlapping subproblems and combining optimal solutions of parts into the whole are the two DP preconditions.',
      },
      {
        id: 'dsa-044',
        subtopic: 'Dynamic Programming',
        difficulty: 'medium',
        points: P.medium,
        q: '0/1 knapsack’s DP table is O(nW) for items n and capacity W. This is…',
        options: [
          'polynomial — P',
          'pseudo-polynomial: exponential in the BIT-length of W',
          'linear',
          'NP-hard to compute',
        ],
        answer: 1,
        explanation:
          'W’s magnitude is exponential in its input size (bits), so O(nW) is pseudo-polynomial — knapsack stays NP-complete yet tractable for modest W.',
      },
      {
        id: 'dsa-045',
        subtopic: 'Dynamic Programming',
        difficulty: 'medium',
        points: P.medium,
        q: 'Longest Common Subsequence of strings of lengths m, n takes…',
        options: ['O(m + n)', 'O(mn) time and space', 'O(m log n)', 'O(2ⁿ) always'],
        answer: 1,
        explanation:
          'Each (i, j) pair is computed once from three neighbours — mn cells. (Space optimises to O(min(m, n)) since only the previous row is needed.)',
      },
      {
        id: 'dsa-046',
        subtopic: 'Dynamic Programming',
        difficulty: 'hard',
        points: P.hard,
        q: 'Memoisation speeds up recursion on overlapping states because…',
        options: [
          'recursion is faster than loops',
          'each distinct state is solved exactly once and reused',
          'it avoids function calls',
          'the compiler inlines it',
        ],
        answer: 1,
        explanation:
          'Without memoisation, overlapping states recompute exponentially many times; caching collapses the work to (number of distinct states) × (transition cost).',
      },
      {
        id: 'dsa-047',
        subtopic: 'Sorting & Searching',
        difficulty: 'medium',
        points: P.medium,
        q: 'Binary search on the ANSWER space applies when the predicate is…',
        options: ['random', 'monotonic — once true, always true beyond a point', 'symmetric', 'periodic'],
        answer: 1,
        explanation:
          'Monotonicity lets each probe discard half the candidate space — e.g. “minimum capacity needed to ship within D days”.',
      },
      {
        id: 'dsa-048',
        subtopic: 'Sorting & Searching',
        difficulty: 'hard',
        points: P.hard,
        q: 'Rotated sorted array [4,5,6,7,0,1,2] — binary search still works in O(log n) by…',
        options: [
          'sorting again first',
          'identifying which half is sorted and checking if the target lies in it',
          'linear scanning the rotation point',
          'using two pointers from both ends',
        ],
        answer: 1,
        explanation:
          'At any mid, at least one half is properly sorted. Test the sorted half’s range; if the target is inside, search there, else the other half — halving every step.',
      },
      {
        id: 'dsa-049',
        subtopic: 'Sorting & Searching',
        difficulty: 'medium',
        points: P.medium,
        q: 'Counting sort beats comparison sorts when…',
        options: [
          'n is small',
          'values span a small known integer range k — O(n + k)',
          'the array is nearly sorted',
          'values are floating point',
        ],
        answer: 1,
        explanation:
          'It tallies frequencies per value instead of comparing pairs, sidestepping the Ω(n log n) comparison-sort lower bound.',
      },
      {
        id: 'dsa-050',
        subtopic: 'Sorting & Searching',
        difficulty: 'hard',
        points: P.hard,
        q: 'The Ω(n log n) lower bound for comparison sorting comes from…',
        options: [
          'hardware limits',
          'the decision tree needing ≥ n! leaves, so height ≥ log₂(n!) = Θ(n log n)',
          'cache behaviour',
          'quick sort’s worst case',
        ],
        answer: 1,
        explanation:
          'Each comparison has 2 outcomes; distinguishing n! permutations needs a decision tree with n! leaves, forcing depth log₂(n!) ≈ n log n. Non-comparison sorts (counting/radix) escape it.',
      },
    ],
  },
  {
    key: 'cpp',
    title: 'C++',
    desc: 'C++ core & STL',
    icon: '/icons/cpp.svg',
    questions: [
      { q: 'Which header gives std::vector?', options: ['<vector>', '<array>', '<list>', '<stdio>'], answer: 0 },
      {
        q: 'RAII stands for…',
        options: [
          'Resource Acquisition Is Initialization',
          'Random Access Iteration Interface',
          'Runtime Allocation In Intervals',
          'Reusable Abstract Inline Items',
        ],
        answer: 0,
      },
      {
        q: 'std::map is typically a…',
        options: ['hash table', 'balanced BST', 'linked list', 'dynamic array'],
        answer: 1,
      },
      { q: 'Which deletes a single heap object?', options: ['free(p)', 'delete p', 'remove(p)', 'clear p'], answer: 1 },
      {
        q: 'A virtual function enables…',
        options: ['static binding', 'runtime polymorphism', 'compile-time consts', 'memory pooling'],
        answer: 1,
      },
      {
        q: 'STL stands for…',
        options: ['Standard Template Library', 'System Type Layer', 'Static Typed Language', 'Stream Template List'],
        answer: 0,
      },
      { q: 'What is a reference in C++?', options: ['a copy', 'an alias', 'a pointer type', 'a macro'], answer: 1 },
      {
        q: 'Which cast is safest for downcasting?',
        options: ['(T)x', 'static_cast', 'dynamic_cast', 'reinterpret_cast'],
        answer: 2,
      },
      {
        q: 'const member function means…',
        options: ['returns const', 'does not modify the object', 'is private', 'is static'],
        answer: 1,
      },
      {
        q: 'Templates provide…',
        options: ['runtime polymorphism', 'generic programming', 'manual memory', 'exceptions'],
        answer: 1,
      },
      {
        id: 'cpp-011',
        subtopic: 'Memory Management',
        difficulty: 'medium',
        points: P.medium,
        q: 'std::unique_ptr vs raw new: unique_ptr’s advantage is…',
        options: [
          'faster allocation',
          'automatic deterministic deletion — RAII, exception-safe',
          'shared ownership',
          'garbage collection',
        ],
        answer: 1,
        explanation:
          'The deleter runs when the unique_ptr leaves scope, even via exceptions — eliminating leak paths that manual delete misses.',
      },
      {
        id: 'cpp-012',
        subtopic: 'Memory Management',
        difficulty: 'medium',
        points: P.medium,
        q: 'std::shared_ptr’s control block tracks…',
        options: [
          'the object’s size',
          'the reference count — the object dies when it hits zero',
          'allocation order',
          'thread IDs',
        ],
        answer: 1,
        explanation:
          'Copies increment, destruction decrements; the last owner destroys the object. Cycles still leak — that is what weak_ptr breaks.',
      },
      {
        id: 'cpp-013',
        subtopic: 'Memory Management',
        difficulty: 'hard',
        points: P.hard,
        q: 'Two objects holding shared_ptr to each other…',
        options: [
          'is fine — counts reach zero',
          'leaks: circular references keep both counts ≥ 1 forever',
          'is a compile error',
          'triggers stack overflow',
        ],
        answer: 1,
        explanation:
          'Each keeps the other alive; neither count falls to zero. Break the cycle with std::weak_ptr on one side.',
      },
      {
        id: 'cpp-014',
        subtopic: 'Memory Management',
        difficulty: 'hard',
        points: P.hard,
        q: 'Returning a local std::vector by value is efficient in modern C++ because of…',
        options: [
          'the copy constructor',
          'move semantics / RVO — the buffer is transferred, not copied',
          'heap cloning',
          'the compiler making it global',
        ],
        answer: 1,
        explanation:
          'Named RVO (NRVO) elides the copy entirely; otherwise the vector’s move constructor steals the heap buffer — O(1) instead of O(n).',
      },
      {
        id: 'cpp-015',
        subtopic: 'References & Pointers',
        difficulty: 'easy',
        points: P.easy,
        q: 'A reference, once bound…',
        options: [
          'can be reseated to another object',
          'cannot be reseated — every use acts on the original',
          'must be null-checked',
          'owns the object',
        ],
        answer: 1,
        explanation:
          'References are aliases, not reassignable pointers — assignment through them writes to the bound object.',
      },
      {
        id: 'cpp-016',
        subtopic: 'References & Pointers',
        difficulty: 'medium',
        points: P.medium,
        q: 'Dangling-pointer risk arises when…',
        options: [
          'a pointer is initialised to nullptr',
          'the pointed-to object is destroyed but the pointer still holds its old address',
          'a pointer is copied',
          'const is applied',
        ],
        answer: 1,
        explanation:
          'Accessing freed storage is undefined behaviour. Smart pointers or careful ownership avoid dangling access.',
      },
      {
        id: 'cpp-017',
        subtopic: 'References & Pointers',
        difficulty: 'medium',
        points: P.medium,
        q: 'Passing a large object as const& instead of by value…',
        options: [
          'copies it once anyway',
          'avoids the copy while promising not to modify it',
          'is slower',
          'forbids modification permanently',
        ],
        answer: 1,
        explanation:
          'const Large& binds without copying — the callee cannot mutate through it. (Small trivially-copyable types can be faster by value.)',
      },
      {
        id: 'cpp-018',
        subtopic: 'References & Pointers',
        difficulty: 'hard',
        points: P.hard,
        q: 'const int* p vs int* const p — the difference is…',
        options: [
          'none — identical',
          'pointer-to-const (data immutable) vs const-pointer (target fixed)',
          'const int* is illegal',
          'int* const is thread-safe',
        ],
        answer: 1,
        explanation:
          'Read right-to-left: “pointer to const int” lets you retarget but not write; “const pointer to int” is fixed but writable-through.',
      },
      {
        id: 'cpp-019',
        subtopic: 'STL Containers',
        difficulty: 'easy',
        points: P.easy,
        q: 'std::vector’s push_back amortised cost is…',
        options: ['O(1)', 'O(log n)', 'O(n) always', 'O(n log n)'],
        answer: 0,
        explanation:
          'Growth by a geometric factor (typically 1.5–2×) means most pushes are O(1); occasional reallocation costs are amortised away.',
      },
      {
        id: 'cpp-020',
        subtopic: 'STL Containers',
        difficulty: 'medium',
        points: P.medium,
        q: 'After a vector REALLOCATION…',
        options: [
          'iterators and pointers to elements remain valid',
          'all iterators, pointers and references are invalidated',
          'only const iterators die',
          'capacity shrinks',
        ],
        answer: 1,
        explanation:
          'Elements move to a new buffer, so old iterators dangle — reserve() ahead of time avoids the reallocations.',
      },
      {
        id: 'cpp-021',
        subtopic: 'STL Containers',
        difficulty: 'medium',
        points: P.medium,
        q: 'std::list vs std::vector for MID-LIST insertion — the winner is…',
        options: [
          'vector — insert is O(log n)',
          'list — O(1) splice at an iterator, no shifting',
          'vector — CPU cache always wins the asymptotics',
          'tie',
        ],
        answer: 1,
        explanation:
          'list rewires two pointers at the position (O(1)); vector must shift the tail (O(n)). In practice, cache-friendliness often makes vector faster anyway for small n.',
      },
      {
        id: 'cpp-022',
        subtopic: 'STL Containers',
        difficulty: 'medium',
        points: P.medium,
        q: 'std::unordered_map offers on average…',
        options: [
          'O(log n) lookup via red-black tree',
          'O(1) hash-based lookup, worst case O(n)',
          'O(n) lookup',
          'sorted iteration for free',
        ],
        answer: 1,
        explanation:
          'Hash buckets give average constant time; adversarial collisions degrade to linear. std::map trades that for ordering and worst-case O(log n).',
      },
      {
        id: 'cpp-023',
        subtopic: 'STL Containers',
        difficulty: 'hard',
        points: P.hard,
        q: 'Erasing from a vector WHILE iterating — the correct pattern is…',
        options: [
          'i++ unconditionally',
          'it = v.erase(it) — erase returns the next valid iterator',
          'clear then refill',
          'it is impossible',
        ],
        answer: 1,
        explanation:
          'erase invalidates the erased iterator and shifts the tail; the returned iterator prevents skipping elements or dereferencing invalid memory.',
      },
      {
        id: 'cpp-024',
        subtopic: 'OOP in C++',
        difficulty: 'medium',
        points: P.medium,
        q: 'A pure virtual function (= 0) makes its class…',
        options: ['final', 'abstract — it cannot be instantiated directly', 'a singleton', 'static'],
        answer: 1,
        explanation:
          'Derived classes must override every pure virtual before instantiation. A destructor can still be pure virtual (with a definition).',
      },
      {
        id: 'cpp-025',
        subtopic: 'OOP in C++',
        difficulty: 'hard',
        points: P.hard,
        q: 'A base class destructor should be virtual when…',
        options: [
          'never — destructors auto-virtual',
          'objects are deleted polymorphically via a base pointer',
          'the class has no members',
          'perf matters',
        ],
        answer: 1,
        explanation:
          'delete basePtr with a non-virtual destructor is UB — only the base destructor runs. Rule: any polymorphic base gets a virtual destructor.',
      },
      {
        id: 'cpp-026',
        subtopic: 'OOP in C++',
        difficulty: 'medium',
        points: P.medium,
        q: 'Multiple inheritance of the SAME base twice (diamond) is disambiguated by…',
        options: [
          'renaming the base',
          'virtual inheritance — one shared base subobject',
          'deleting one path',
          'static_cast',
        ],
        answer: 1,
        explanation:
          'class B : virtual public A makes both D→B→A and D→C→A share a single A instance, removing the ambiguity.',
      },
      {
        id: 'cpp-027',
        subtopic: 'OOP in C++',
        difficulty: 'medium',
        points: P.medium,
        q: 'The override keyword on a derived method…',
        options: [
          'is decoration with no effect',
          'asks the compiler to error if the base signature does not match',
          'makes the method virtual for the first time',
          'disables dynamic dispatch',
        ],
        answer: 1,
        explanation:
          'Typoed signatures (missing const, wrong parameter type) silently create overloads — override turns that silent bug into a compile error.',
      },
      {
        id: 'cpp-028',
        subtopic: 'Language Semantics',
        difficulty: 'hard',
        points: P.hard,
        q: 'Undefined behaviour (signed overflow, out-of-bounds access…) means…',
        options: [
          'the program crashes immediately',
          'the compiler may assume it never happens — any behaviour is allowed, including silent miscompilation',
          'the OS intervenes',
          'results are merely unpredictable but safe',
        ],
        answer: 1,
        explanation:
          'UB is not “random result” — optimisers exploit its impossibility to reorder/delete code, so effects can appear far from the cause. Sanitisers catch it at runtime.',
      },
      {
        id: 'cpp-029',
        subtopic: 'Language Semantics',
        difficulty: 'medium',
        points: P.medium,
        q: 'int x = 7 / 2; in C++ gives…',
        options: ['3.5', '3 — integer division truncates toward zero', '4 — rounds to nearest', 'a compile error'],
        answer: 1,
        explanation:
          'Both operands are ints, so the result is int: 3 (truncation toward zero — note -7/2 is -3, unlike Python’s floor division).',
      },
      {
        id: 'cpp-030',
        subtopic: 'Language Semantics',
        difficulty: 'medium',
        points: P.medium,
        q: 'i++ vs ++i for a heavy iterator type — ++i is preferred because…',
        options: [
          'they are identical always',
          'pre-increment does not create a temporary copy of the old state',
          '++i is thread-safe',
          'i++ is deprecated',
        ],
        answer: 1,
        explanation:
          'Post-increment must materialise the previous value before changing state; for class types that copy can be costly. For ints, compilers make them equal.',
      },
      {
        id: 'cpp-031',
        subtopic: 'Language Semantics',
        difficulty: 'hard',
        points: P.hard,
        q: 'Signed integer overflow in C++ is…',
        options: [
          'well-defined wraparound like unsigned',
          'undefined behaviour — compilers may exploit it for optimisation',
          'defined as saturation',
          'a runtime exception',
        ],
        answer: 1,
        explanation:
          'Unlike unsigned (defined mod 2ⁿ), signed overflow is UB — e.g. a loop condition like i <= n + 1 can be “proven” always-true and turned into an infinite loop.',
      },
      {
        id: 'cpp-032',
        subtopic: 'Templates',
        difficulty: 'medium',
        points: P.medium,
        q: 'Templates are instantiated…',
        options: [
          'at runtime per call',
          'at compile time for each concrete type used',
          'by the linker once per program',
          'lazily by the OS',
        ],
        answer: 1,
        explanation:
          'The compiler stamps out a separate function/class per type combination — that is why template code lives in headers and binary size can grow.',
      },
      {
        id: 'cpp-033',
        subtopic: 'Templates',
        difficulty: 'hard',
        points: P.hard,
        q: 'C++20 concepts (requires std::integral<T>) primarily improve…',
        options: [
          'runtime speed',
          'compile-time error messages and constraint checking',
          'binary size',
          'thread safety',
        ],
        answer: 1,
        explanation:
          'Concepts constrain which types instantiate the template, replacing pages of cryptic SFINAE errors with a clear constraint violation.',
      },
      {
        id: 'cpp-034',
        subtopic: 'STL Algorithms',
        difficulty: 'medium',
        points: P.medium,
        q: 'std::sort vs std::stable_sort: stable_sort…',
        options: [
          'is always faster',
          'preserves the relative order of equal elements (usually mergesort-based)',
          'uses no extra memory',
          'only works on ints',
        ],
        answer: 1,
        explanation:
          'Stability matters when sorting by a secondary key after a primary sort. std::sort is typically introsort — faster but not stable.',
      },
      {
        id: 'cpp-035',
        subtopic: 'STL Algorithms',
        difficulty: 'medium',
        points: P.medium,
        q: 'The erase–remove idiom (v.erase(std::remove(...), v.end())) exists because…',
        options: [
          'remove is slow',
          'algorithms cannot change container SIZE — remove only shifts elements and returns the new logical end',
          'erase needs sorted input',
          'compilers require it',
        ],
        answer: 1,
        explanation:
          'std::remove compacts survivors to the front and hands back the new end iterator; the actual shrink is erase’s job. (C++20: std::erase_if.)',
      },
      {
        id: 'cpp-036',
        subtopic: 'STL Algorithms',
        difficulty: 'hard',
        points: P.hard,
        q: 'Calling std::sort with a comparator that says a < b AND b < a (inconsistent) causes…',
        options: [
          'a compile error',
          'undefined behaviour — typically crashes inside the sort',
          'silent correct output',
          'an exception',
        ],
        answer: 1,
        explanation:
          'std::sort requires a strict weak ordering; inconsistent comparators break its invariants and can read out of bounds.',
      },
      {
        id: 'cpp-037',
        subtopic: 'Move Semantics',
        difficulty: 'hard',
        points: P.hard,
        q: 'std::move(obj) actually…',
        options: [
          'moves the data immediately',
          'is just a cast to rvalue-reference — it enables move, performs nothing itself',
          'copies then deletes',
          'freezes the object',
        ],
        answer: 1,
        explanation:
          'std::move is static_cast<T&&>: it marks the expression as movable so a move constructor/assignment is selected. The transfer happens in that constructor.',
      },
      {
        id: 'cpp-038',
        subtopic: 'Move Semantics',
        difficulty: 'medium',
        points: P.medium,
        q: 'After std::string b = std::move(a); — a is…',
        options: [
          'guaranteed empty',
          'in a valid but unspecified state — do not read it, but you may reassign it',
          'a dangling pointer',
          'unchanged',
        ],
        answer: 1,
        explanation:
          'Moved-from objects are still destructible/assignable, but their contents are unspecified. Standard discipline: leave, don’t inspect.',
      },
      {
        id: 'cpp-039',
        subtopic: 'Concurrency',
        difficulty: 'medium',
        points: P.medium,
        q: 'Two threads doing counter++ without synchronisation…',
        options: [
          'always produce the right total',
          'race: read-modify-write can interleave, losing increments (UB)',
          'are serialised by the compiler',
          'crash immediately',
        ],
        answer: 1,
        explanation:
          'counter++ is three steps (load, add, store). Interleavings lose updates — and in the C++ memory model it is formally a data race, i.e. UB. Use std::atomic.',
      },
      {
        id: 'cpp-040',
        subtopic: 'Concurrency',
        difficulty: 'hard',
        points: P.hard,
        q: 'std::mutex must be unlocked exactly by…',
        options: [
          'any thread',
          'the thread that locked it — prefer RAII wrappers like std::lock_guard',
          'the main thread only',
          'the OS',
        ],
        answer: 1,
        explanation:
          'Manual lock/unlock leaks the lock on early return/exception. lock_guard acquires in construction and releases in destruction — exception-safe by design.',
      },
      {
        id: 'cpp-041',
        subtopic: 'STL Containers',
        difficulty: 'medium',
        points: P.medium,
        q: 'std::vector::reserve(n) vs resize(n): reserve…',
        options: [
          'creates n elements',
          'only pre-allocates capacity — size stays unchanged',
          'is identical to resize',
          'shrinks the buffer',
        ],
        answer: 1,
        explanation:
          'reserve touches capacity only (no constructors run); resize value-initialises n elements. reserve is the right tool before known-size bulk pushes.',
      },
      {
        id: 'cpp-042',
        subtopic: 'References & Pointers',
        difficulty: 'medium',
        points: P.medium,
        q: 'Returning a reference to a LOCAL variable…',
        options: [
          'is fine — references keep objects alive',
          'dangles: the local dies at return, the reference is UB to use',
          'is required by RAII',
          'is legal if the local is const',
        ],
        answer: 1,
        explanation:
          'The referent is destroyed when the stack frame exits; unlike returning by value, no copy/move saves you. Return locals BY VALUE instead.',
      },
      {
        id: 'cpp-043',
        subtopic: 'Language Semantics',
        difficulty: 'medium',
        points: P.medium,
        q: 'The static keyword on a file-scope function…',
        options: [
          'makes it faster',
          'gives it internal linkage — visible only in that translation unit',
          'makes it thread-safe',
          'is deprecated',
        ],
        answer: 1,
        explanation:
          'static (or an anonymous namespace) limits visibility to the TU, preventing symbol collisions and letting the optimizer reason locally.',
      },
      {
        id: 'cpp-044',
        subtopic: 'STL Containers',
        difficulty: 'hard',
        points: P.hard,
        q: 'Iterating a std::map and erasing current element safely (pre-C++20):',
        options: [
          'it++ then erase(it)',
          'it = m.erase(it) — erase returns the next iterator; it++ first is UB',
          'clear then re-add',
          'reverse iteration always',
        ],
        answer: 1,
        explanation:
          'map::erase invalidates only the erased iterator and returns the next one. erase(it++) used to be the idiom, but erase-returning is clearer and correct.',
      },
      {
        id: 'cpp-045',
        subtopic: 'Move Semantics',
        difficulty: 'medium',
        points: P.medium,
        q: 'The rule of five exists because declaring any of (destructor, copy, move ops)…',
        options: [
          'is purely stylistic',
          'usually signals resource ownership, so the other four need correct definitions or = delete/default',
          'is forbidden in C++17',
          'only matters for templates',
        ],
        answer: 1,
        explanation:
          'A custom destructor almost always means raw-resource ownership; the compiler-generated copies would shallow-copy it — define or delete the rest explicitly.',
      },
      {
        id: 'cpp-046',
        subtopic: 'Memory Management',
        difficulty: 'medium',
        points: P.medium,
        q: 'Memory allocated with new[] must be freed with…',
        options: [
          'free()',
          'delete[] — mixing new[] with delete is undefined behaviour',
          'delete (same thing)',
          'std::free',
        ],
        answer: 1,
        explanation:
          'new[] records the element count for per-element destructors; delete[] reads it. Mismatched forms are UB — another reason to prefer std::vector/unique_ptr<T[]>.',
      },
      {
        id: 'cpp-047',
        subtopic: 'OOP in C++',
        difficulty: 'medium',
        points: P.medium,
        q: 'Calling a virtual function from a base-class CONSTRUCTOR dispatches to…',
        options: [
          'the derived override — full polymorphism',
          'the BASE version — the dynamic type is still the base during construction',
          'nothing — it is skipped',
          'a random override',
        ],
        answer: 1,
        explanation:
          'During base construction the dynamic type is the base class, so the override never runs — unlike Java. “Never call virtuals in ctors/dtors.”',
      },
      {
        id: 'cpp-048',
        subtopic: 'Language Semantics',
        difficulty: 'easy',
        points: P.easy,
        q: 'auto keyword (C++11+) deduces the type…',
        options: ['at runtime', 'at compile time from the initializer', 'as void*', 'as the return type'],
        answer: 1,
        explanation:
          'auto is compile-time type deduction (template rules) — zero runtime cost, less verbosity, and fewer narrow-char mistakes.',
      },
      {
        id: 'cpp-049',
        subtopic: 'Concurrency',
        difficulty: 'medium',
        points: P.medium,
        q: 'std::atomic<int> x; x.fetch_add(1) guarantees…',
        options: [
          'only visibility',
          'atomic read-modify-write — no lost updates, no data race',
          'a lock is taken always',
          'sequential printing',
        ],
        answer: 1,
        explanation:
          'Atomic RMW operations complete indivisibly; default memory ordering is seq_cst (weaker orders are opt-in for performance).',
      },
      {
        id: 'cpp-050',
        subtopic: 'Templates',
        difficulty: 'hard',
        points: P.hard,
        q: 'Template code is usually defined in HEADERS because…',
        options: [
          'headers are faster to parse',
          'the compiler needs the full definition visible in every TU to instantiate per-type versions',
          'the linker deduplicates functions',
          'static libraries forbid templates',
        ],
        answer: 1,
        explanation:
          'Instantiation happens per translation unit at compile time; without the body, the compiler cannot stamp out the typed copy (extern templates are the opt-out).',
      },
    ],
  },
  // __JS__
]

export function getTopic(key: string): ArenaTopic | undefined {
  return ARENA_TOPICS.find((t) => t.key === key)
}

/** Deterministic per-session shuffle so retries differ without a DB round-trip. */
export function pickRound(topic: ArenaTopic, count = 5): ArenaQuestion[] {
  const pool = [...topic.questions]
  const out: ArenaQuestion[] = []
  while (out.length < count && pool.length > 0) {
    out.push(pool.splice(Math.floor(Math.random() * pool.length), 1)[0])
  }
  return out
}
